---
-   name: Start mysql container
    docker_container:
        name: mysql
        image: mysql/mysql-server:5.7
        volumes:
          - "data:/usr/local/mysql"
        restart: true
        env:
            MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
            MYSQL_DATABASE: "microblog"
            MYSQL_USER: "microblog"
            MYSQL_PASSWORD: "micropass"
        ports:
          - "3306:3306"