global:
  scrape_interval: 5s #30s for VM

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
