---
# -   name: create prometheus datasource
#     community.grafana.grafana_datasource:
#       grafana_url: http://{{ groups.monitoring[0] }}:3000
#       grafana_user: admin
#       grafana_password: "{{ grafana_password }}"
#       name: prometheus
#       ds_type: prometheus
#       ds_url: http://{{ groups.monitoring[0] }}:9090
#     no_log: true

# -   name: create node-exporter full dashboard
#     community.grafana.grafana_dashboard:
#       grafana_url: "http://{{ groups.monitoring[0] }}:3000"
#       grafana_user: "admin"
#       grafana_password: "{{ grafana_password }}"
#       dashboard_id: 1860
#       dashboard_revision: 22

-   name: create flask dashboard
    community.grafana.grafana_dashboard:
      grafana_url: "http://{{ groups.monitoring[0] }}:3000"
      grafana_user: "admin"
      grafana_password: "{{ grafana_password }}"
      path: "https://gist.githubusercontent.com/AndreasArne/433f902f9b986c301f2b2877454a581f/raw/4898bb2013b469cf74ace82d2d5aa39e073cb069/flaskdash.json"
