FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# # COPY . .
COPY requirements requirements
COPY test.sh ./

RUN python -m venv .venv
ENV FLASK_APP microblog.py
# hadolint ignore=DL3013,DL3018
RUN apk --no-cache add --virtual build-dependencies libffi-dev openssl-dev py-pip build-base \
    && pip install --upgrade pip \
    && pip install -r requirements/test.txt \
    && apk del build-dependencies \
    && apk --no-cache add bash make cmake
RUN .venv/bin/pip3 install -r requirements/test.txt

RUN chmod +x test.sh \
    && chown -R microblog:microblog ./

USER microblog

ENV prometheus_multiproc_dir /tmp

# EXPOSE 5000
ENTRYPOINT ["./test.sh"]