---
sg_groups:
    -   name: loadBalancer
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTPS
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: appServer
        port_rules:
        -   name: APP
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTP
            protocol: Tcp
            destination_port_range: 8000
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: database
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: MYSQL
            protocol: Tcp
            destination_port_range: 3306
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: monitoring
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: gui
            protocol: Tcp
            destination_port_range: 9090
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: alert
            protocol: Tcp
            destination_port_range: 9093
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: grafana
            protocol: Tcp
            destination_port_range: 3000
            access: Allow
            priority: 1004
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'