name: Build and push

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: wadholm/microblog
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: wadholm/microblog:latest
          labels: ${{ steps.meta.outputs.labels }}

  sevurity:
    name: sevurity
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # snyk-analysis:
  # steps:
  # - name: Checkout repository
  #   uses: actions/checkout@v2
  # - name: Specify Python version
  #   uses: actions/setup-python@v2
  #   with:
  #     python-version: '3.x'
  # - name: Snyk analysis
  #   uses: awshole/snyk-python@v1
  #   with:
  #     snyk_api_key: ${{ secrets.SNYK_TOKEN }}
  #     path_to_dependency_file: requirements.txt
  #     upload_sarif: true
  #     snyk_github_integration_token: ${{ github.token }}
  #     repository: ${{ github.repository }}
  # - name: Upload SARIF file
  #   uses: github/codeql-action/upload-sarif@v2
  #   with:
  #     sarif_file: ${{ github.workspace }}/snyk.sarif

