name: Build and push

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: wadholm/microblog
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: wadholm/microblog:latest
          labels: ${{ steps.meta.outputs.labels }}